# -*- coding: utf-8 -*-
"""NLP Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_78v2SHQ3zeSq-v47GDB8kN8PvQxiCE
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
# %matplotlib inline

# download the names.txt file from github
!wget https://raw.githubusercontent.com/lhaggerty18/NLP-Exercise-2/refs/heads/main/taxonomicnames.csv

allData = pd.read_csv("taxonomicnames.csv")

pre1850 = allData[allData['year'] < 1850]
post1850 = allData[allData['year'] >= 1850]

words = list(pre1850['taxon'])
len(words)

min(len(w) for w in words)

max(len(w) for w in words)

# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
vocab_size = len(itos)
print(itos)
print(vocab_size)

# build the dataset
block_size = 16 # context length: how many characters do we take to predict the next one?

def build_dataset(words):
  X, Y = [], []

  for w in words:
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y

n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
Xtr,  Ytr  = build_dataset(words[:n1])     # 80%
Xdev, Ydev = build_dataset(words[n1:n2])   # 10%
Xte,  Yte  = build_dataset(words[n2:])     # 10%

words2 = list(post1850['taxon'])
Xte_modern,  Yte_modern = build_dataset(words2)

for x,y in zip(Xtr[:18], Ytr[:18]):
  print(''.join(itos[ix.item()] for ix in x), '-->', itos[y.item()])

# Near copy paste of the layers we have developed in Part 3

# -----------------------------------------------------------------------------------------------
class Linear:

  def __init__(self, fan_in, fan_out, bias=True):
    self.weight = torch.randn((fan_in, fan_out)) / fan_in**0.5 # note: kaiming init
    self.bias = torch.zeros(fan_out) if bias else None

  def __call__(self, x):
    self.out = x @ self.weight
    if self.bias is not None:
      self.out += self.bias
    return self.out

  def parameters(self):
    return [self.weight] + ([] if self.bias is None else [self.bias])

# -----------------------------------------------------------------------------------------------
class BatchNorm1d:

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.momentum = momentum
    self.training = True
    # parameters (trained with backprop)
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
    # buffers (trained with a running 'momentum update')
    self.running_mean = torch.zeros(dim)
    self.running_var = torch.ones(dim)

  def __call__(self, x):
    # calculate the forward pass
    if self.training:
      if x.ndim == 2:
        dim = 0
      elif x.ndim == 3:
        dim = (0,1)
      xmean = x.mean(dim, keepdim=True) # batch mean
      xvar = x.var(dim, keepdim=True) # batch variance
    else:
      xmean = self.running_mean
      xvar = self.running_var
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    # update the buffers
    if self.training:
      with torch.no_grad():
        self.running_mean = (1 - self.momentum) * self.running_mean + self.momentum * xmean
        self.running_var = (1 - self.momentum) * self.running_var + self.momentum * xvar
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

# -----------------------------------------------------------------------------------------------
class Tanh:
  def __call__(self, x):
    self.out = torch.tanh(x)
    return self.out
  def parameters(self):
    return []

# -----------------------------------------------------------------------------------------------
class Embedding:

  def __init__(self, num_embeddings, embedding_dim):
    self.weight = torch.randn((num_embeddings, embedding_dim))

  def __call__(self, IX):
    self.out = self.weight[IX]
    return self.out

  def parameters(self):
    return [self.weight]

# -----------------------------------------------------------------------------------------------
class FlattenConsecutive:

  def __init__(self, n):
    self.n = n

  def __call__(self, x):
    B, T, C = x.shape
    x = x.view(B, T//self.n, C*self.n)
    if x.shape[1] == 1:
      x = x.squeeze(1)
    self.out = x
    return self.out

  def parameters(self):
    return []

# -----------------------------------------------------------------------------------------------
class Sequential:

  def __init__(self, layers):
    self.layers = layers

  def __call__(self, x):
    for layer in self.layers:
      x = layer(x)
    self.out = x
    return self.out

  def parameters(self):
    # get parameters of all layers and stretch them out into one list
    return [p for layer in self.layers for p in layer.parameters()]

torch.manual_seed(42); # seed rng for reproducibility

# hierarchical network
n_embd = 24 # the dimensionality of the character embedding vectors
n_hidden = 200 # the number of neurons in the hidden layer of the MLP
model = Sequential([
  Embedding(vocab_size, n_embd),
  FlattenConsecutive(2), Linear(n_embd*2, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  FlattenConsecutive(2), Linear(n_hidden*2, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  FlattenConsecutive(2), Linear(n_hidden*2, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  FlattenConsecutive(2), Linear(n_hidden*2, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(n_hidden, vocab_size),
])

# parameter init
with torch.no_grad():
  model.layers[-1].weight *= 0.1 # last layer make less confident

parameters = model.parameters()
print(sum(p.nelement() for p in parameters)) # number of parameters in total
for p in parameters:
  p.requires_grad = True

# same optimization as last time
max_steps = 80001
batch_size = 64
lossi = []

for i in range(max_steps):

  # minibatch construct
  ix = torch.randint(0, Xtr.shape[0], (batch_size,))
  Xb, Yb = Xtr[ix], Ytr[ix] # batch X,Y

  # forward pass
  logits = model(Xb)
  loss = F.cross_entropy(logits, Yb) # loss function

  # backward pass
  for p in parameters:
    p.grad = None
  loss.backward()

  # update: simple SGD
  lr = 0.1
  for p in parameters:
    p.data += -lr * p.grad

  # track stats
  if i % 10000 == 0: # print every once in a while
    print(f'{i:7d}/{max_steps:7d}: {loss.item():.4f}')
  lossi.append(loss.log10().item())

plt.plot(torch.tensor(lossi[:(max_steps-1)]).view(-1, 1000).mean(1))

# put layers into eval mode (needed for batchnorm especially)
for layer in model.layers:
  layer.training = False
  print(layer.__class__.__name__, ':', tuple(layer.out.shape))

# evaluate the loss
@torch.no_grad() # this decorator disables gradient tracking inside pytorch
def split_loss(split):
  x,y = {
    'train': (Xtr, Ytr),
    'val': (Xdev, Ydev),
    'test': (Xte, Yte),
    'modern': (Xte_modern, Yte_modern),
  }[split]
  logits = model(x)
  loss = F.cross_entropy(logits, y)
  print(split, loss.item())

#split_loss('train')
split_loss('val')
split_loss('test')
split_loss('modern')

"""# Production Log

*   block_size: 8, batch_size: 32, n_embd: 10, n_hidden = 64, LR: 0.1, steps: 20000
    * train 1.489462971687317
    * val 1.997892141342163
*   block_size: 8, batch_size: 32, n_embd: 10, n_hidden = 128, LR: 0.1, steps: 20000
    * train 1.3984721899032593
    * val 1.94968843460083
*   block_size: 8, batch_size: 32, n_embd: 24, n_hidden = 128, LR: 0.1, steps: 20000
    * train 1.3615820407867432
    * val 1.916917085647583
*   block_size: 8, batch_size: 32, n_embd: 24, n_hidden = 128, LR: 0.1, steps: 20000
    * train 1.3615820407867432
    * val 1.916917085647583
*   block_size: 16, batch_size: 32, n_embd: 10, n_hidden = 64, LR: 0.1, steps: 20000
    * train 1.4431943893432617
    * val 2.000748872756958
*   block_size: 8, batch_size: 32, n_embd: 12, n_hidden = 200, LR: 0.1, steps: 20000
    * train 1.3577953577041626
    * val 1.935235619544983
*   block_size: 8, batch_size: 64, n_embd: 12, n_hidden = 200, LR: 0.1, steps: 20001
    * train 1.1305
    * val 1.857035756111145
*   block_size: 8, batch_size: 64, n_embd: 24, n_hidden = 200, LR: 0.1, steps: 20001
    * train 1.1877
    * val 1.8254183530807495
*   block_size: 16, batch_size: 64, n_embd: 24, n_hidden = 200, LR: 0.1, steps: 20001
    * train 1.4044
    * val 1.8257302045822144
*   block_size: 16, batch_size: 64, n_embd: 24, n_hidden = 200, LR: 0.1, steps: 80001
    * train 1.0266
    * val 1.7805094718933105
    * test 2.157536506652832
"""

# sample from the model
for _ in range(100):

    out = []
    context = [0] * block_size # initialize with all ...
    while True:
      # forward pass the neural net
      logits = model(torch.tensor([context]))
      probs = F.softmax(logits, dim=1)
      # sample from the distribution
      ix = torch.multinomial(probs, num_samples=1).item()
      # shift the context window and track the samples
      context = context[1:] + [ix]
      out.append(ix)
      # if we sample the special '.' token, break
      if ix == 0:
        break

    print(''.join(itos[i] for i in out)) # decode and print the generated word